baseURL = 'https://example.org/'
disablePathToLower = true
languageCode = 'en-us'
title = 'Errorly'
theme = "hugo-bearcub"
copyright = "Errorly"

[params]
    madewith="Made With Code"
    favicon = "errorly.jpg"
    [markup]
      [markup.highlight]
        lineNos = true
        lineNumbersInTable = false
        noClasses = false

      [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true


          # Navigation Menu
          [[menu.main]]
              name = "Home"
              url = "/"
              weight = 1

          [[menu.main]]
              name = "Projects"
              url = "/projects/"
              weight = 2

          [[menu.main]]
              name = "Roadmap"
              url = "/roadmap/"
              weight = 3
